# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - CI_CD_Pipeline
  pull_request:
    branches:
      - CI_CD_Pipeline

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Make sure the version of Node.js is compatible with our project

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
